---
- hosts: localhost
  name: Create LS Root Vols
  gather_facts: false
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Volume 1 Create
    na_ontap_volume:
      state: present
      name: "{{ lsvol1name }}"
      vserver: "{{ vservername }}"
      aggregate_name: "{{ aggr1 }}"
      size: "{{ lsvol1size }}"
      size_unit: gb
      type: DP
      policy: default
      percent_snapshot_space: 0
      space_guarantee: none
      <<: *login
  - debug: msg="Volume {{ lsvol1name }} has been created."
  - name: Volume 2 Create
    na_ontap_volume:
      state: present
      name: "{{ lsvol2name }}"
      vserver: "{{ vservername }}"
      aggregate_name: "{{ aggr2 }}"
      size: "{{ lsvol2size }}"
      size_unit: gb
      type: DP
      policy: default
      percent_snapshot_space: 0
      space_guarantee: none
      <<: *login
  - debug: msg="Volume {{ lsvol2name }} has been created."

