---
- hosts: localhost
  name: Create LS Mirror
  gather_facts: false
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Create First LS Mirror
    na_ontap_snapmirror:
      state: present
      source_volume: "{{ lsvolsrc }}"
      destination_volume: "{{ lsvol1name }}"
      source_vserver: "{{ vservername }}"
      destination_vserver: "{{ vservername }}"
      schedule: hourly
      relationship_type: load_sharing
      <<: *login
  - debug: msg="First LS Mirror Created."
  - name: Create Second LS Mirror
    na_ontap_snapmirror:
      state: present
      source_volume: "{{ lsvolsrc }}"
      destination_volume: "{{ lsvol2name }}"
      source_vserver: "{{ vservername }}"
      destination_vserver: "{{ vservername }}"
      schedule: hourly
      relationship_type: load_sharing
      <<: *login
  - debug: msg="Second LS Mirror Created."
  - name: sleep for 20 seconds to allow for Volume 1 Snapmirror Initialization
    wait_for:
      timeout: 20
  - name: Initialize Snapmirror for Volume 2 # This is due to na_ontap_snapmirror not initializing second LS Mirror
    na_ontap_command:
      command: ['snapmirror', 'initialize', '-source-path', "{{ sourcecluster + '://' + vservername + '/' + lsvolsrc }}", '-destination-path', "{{ sourcecluster + '://' + vservername + '/' + lsvol2name }}"]
      privilege: admin
      <<: *login
  - debug: msg="Second LS Mirror initialized."
 



